### ISSUE TITLE
[bug] Unhandled Runtime Error  http://localhost:31392/

### ISSUE THREAD

**Issue by pleabargain** [mediar-ai/screenpipe#1046]
**describe the bug**
http://localhost:31392/
Unhandled Runtime Error 

**system info**
win11

**additional context**
running SP from CLI

```
Error: Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  ...
    <PopperAnchor asChild={true} __scopePopper={{Popper:[...]}}>
      <Primitive.div asChild={true} ref={function}>
        <Slot ref={function}>
          <SlotClone ref={function}>
            <Primitive.button aria-describedby={undefined} data-state="closed" asChild={true} ref={function} ...>
              <Slot aria-describedby={undefined} data-state="closed" onPointerMove={function handleEvent} ...>
                <SlotClone aria-describedby={undefined} data-state="closed" onPointerMove={function handleEvent} ...>
                  <div className={"relative..."} aria-describedby={undefined} data-state="closed" ...>
                    <div>
                    <_c className="cursor-poi..." onClick={function onClick}>
                      <div ref={null} className="rounded-lg..." onClick={function onClick}>
                        <_c8 className="p-3 flex f...">
                          <div ref={null} className="p-3 flex f...">
                            <div>
                            <div className="flex flex-...">
                              <Badge>
                              <Badge>
                              <Badge>
                              <Badge>
                                <div className="inline-fle...">
+                                 12/24/2024, 12:34:56 PM
-                                 12/24/2024, 12:34:55 PM

    at throwOnHydrationMismatch (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:2659:56)
    at completeWork (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7367:36)
    at runWithFiberInDEV (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:631:20)
    at completeUnitOfWork (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8020:23)
    at performUnitOfWork (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7957:28)
    at workLoopConcurrent (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7951:58)
    at renderRootConcurrent (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7933:71)
    at performWorkOnRoot (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7565:175)
    at performWorkOnRootViaSchedulerTask (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8394:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:31392/_next/static/chunks/node_modules_next_dist_compiled_107ce8._.js:2353:64)
```

**Comment by louis030195** [comment]
what problem is it causing?
