### ISSUE TITLE
windows install screenpipe didnt work

### ISSUE THREAD

**Issue by tens0rcat** [mediar-ai/screenpipe#387]
also installed 

choco install git mingw

But then it still failed 

```
error: failed to run custom build command for `ort-sys v2.0.0-rc.6`

Caused by:
  process didn't exit successfully: `C:\xxxxxxxxx\Projects\screenpipe\target\release\build\ort-sys-b9802a1ce791c66c\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBONNXRUNTIME_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBONNXRUNTIME_STATIC
  cargo:rerun-if-env-changed=LIBONNXRUNTIME_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  onnxruntime not found using pkg-config, falling back to manual setup.
  cargo:rerun-if-env-changed=ORT_LIB_LOCATION
  cargo:rerun-if-env-changed=ORT_LIB_PROFILE
  selected feature set: cu12

  --- stderr
  thread 'main' panicked at C:\xxxxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-sys-2.0.0-rc.6\build.rs:358:17:
  downloaded binaries not available for target x86_64-pc-windows-gnu (note: also requested features `cu12`)
  you may have to compile ONNX Runtime from source
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `v8 v0.106.0`
```

**Comment by tribhuwan-kumar** [comment]
@tens0rcat use this [gist](https://gist.github.com/tribhuwan-kumar/3d92219be32a762148d9bd5b557e519f) for windows

**Comment by tens0rcat** [comment]
I just went straight down the instructions for the windows build. This was from the cargo build, and just the first error (the others were basically the same thing).  

cargo build --release --features cuda

[output.txt](https://github.com/user-attachments/files/17198005/output.txt)

**Comment by tens0rcat** [comment]
output without cuda

[output2.txt](https://github.com/user-attachments/files/17198069/output2.txt)

**Comment by tribhuwan-kumar** [comment]
> I just went straight down the instructions for the windows build. This was from the cargo build, and just the first error (the others were basically the same thing).
> 
> cargo build --release --features cuda -v
> 
> [output.txt](https://github.com/user-attachments/files/17198005/output.txt)

you're getting [this](https://github.com/mediar-ai/screenpipe/issues/319#issuecomment-2376472197) same issue, uninstall the `rust` you have installed from `choco` and install `rust` from [rust up](https://rustup.rs/), also you haven't installed [python](https://www.python.org/downloads/release/python-3126/) & you can ignore the `cuda` option!

**Comment by tens0rcat** [comment]
okk, installing the other rust worked and the build completed.  Trying to build the desktop app and 

```
2024-09-30 21:33:42 (6.26 MB/s) - 'tesseract-setup.exe' saved [50175248/50175248]

bun: Permission denied:
187 |   const tesseractInstaller = `${tesseractName}.exe`
188 |
189 |   if (!(await fs.exists('tesseract'))) {
190 |           console.log('Setting up Tesseract for Windows...')
191 |           await $`${wgetPath} -nc  --no-check-certificate --show-progress ${tesseractUrl} -O ${tesseractInstaller}`
192 |           await $`"${process.cwd()}\\${tesseractInstaller}" /S /D=C:\\Program Files\\Tesseract-OCR`
                     ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "bun: Permission denied: \n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at C:\xxxxxxxxxx\Projects\screenpipe\screenpipe-app-tauri\scripts\pre_build.js:192:9

Bun v1.1.29 (Windows x64)
```

I ran the tesseract-setup.exe that it downloaded by hand and it installed, but then redoing the prebuild gave basically the same error

**Comment by tribhuwan-kumar** [comment]
@tens0rcat use adminstrator terminal to run `pre_build.js`, it'll execute the `tesseract` installer

**Comment by tens0rcat** [comment]
ok, still better, but it's not using the environment var VCPKG_ROOT in the pre-build so I a getting this:

```
bun scripts\pre_build.js
cwd C:\Users\DougW\Projects\screenpipe\screenpipe-app-tauri\src-tauri
wget found at: C:\ProgramData\chocolatey\bin\wget.exe
Copying screenpipe binary...
Screenpipe binary copied successfully from C:\Users\DougW\Projects\screenpipe\target\release\screenpipe.exe
Tesseract for Windows already exists.
ONNX Runtime libraries for Windows already exists.
236 |           await $`rm ${config.windows.clblastName}.zip`
237 |           await $`rm ${config.windows.clblastName}.7z`
238 |   }
239 |
240 |   // Setup vcpkg packages
241 |   await $`C:\\vcpkg\\vcpkg.exe install ${config.windows.vcpkgPackages}`.quiet()
                     ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at C:\Users\DougW\Projects\screenpipe\screenpipe-app-tauri\scripts\pre_build.js:241:8

Bun v1.1.29 (Windows x64)
```

**Comment by tens0rcat** [comment]
I copied the vcpkg stuff where it wanted it then re-ran the bun prebuild....

It output this and has just hung.  (CPU is basically 100% idle)

```
>bun scripts\pre_build.js
cwd C:\Users\DougW\Projects\screenpipe\screenpipe-app-tauri\src-tauri
wget found at: C:\ProgramData\chocolatey\bin\wget.exe
Copying screenpipe binary...
Screenpipe binary copied successfully from C:\Users\DougW\Projects\screenpipe\target\release\screenpipe.exe
Tesseract for Windows already exists.
ONNX Runtime libraries for Windows already exists.
```

**Comment by tens0rcat** [comment]
also having to get latest node (had a v14. something installed already) now 22.9

**Comment by tens0rcat** [comment]
ok, it built, installed, ran, updated (lol) and seems running fine, I'm getting ocr from the screen.  I'll have to mess with the ai config for ollama tomorrow.  

Thank you for all your help!

**Comment by alihaskar** [comment]
same error

**Comment by louis030195** [comment]
we should make tesseract optional on windows, it's kind of a pain in the ass and windows native much better

**Comment by tens0rcat** [comment]
hmm, can't get ollama llama3.2 to work, I tried the recommended URL (which in my case is HTTP://192.168.2.12:11434) with the /v1, /v2, and no path (the vscode plugins don't require a path).  When I go to the nopath I get the response "Ollama is running". From within screenpipe, in all cases, I get the response: 
![image](https://github.com/user-attachments/assets/472b0d4f-ba58-470b-9236-69d488fbefd0)  I tried both blank for the API key and NA, no difference.

**Comment by tens0rcat** [comment]
tesseract is OCR right? it's not even an option in the system I built.  Only "windows native"

**Comment by tens0rcat** [comment]
Ollama is working, if I go to the URL in my browser it says it works, it works with VS Code (Continue and ClaudeDev plugins), OpenWebUI, etc. So I know it's not being blocked.

**Comment by louis030195** [comment]
> Ollama is working, if I go to the URL in my browser it says it works, it works with VS Code (Continue and ClaudeDev plugins), OpenWebUI, etc. So I know it's not being blocked.
> 
> Edit: or are you saying this needs to be added as an environment variable on my workstation?

yes ollama blocks Tauri and web browsers access so you need to let access like this

**Comment by tens0rcat** [comment]
do I need to add that as an env var on my workstation, or the ai server that is running ollama?

heh, why not both?  Let's see

**Comment by tens0rcat** [comment]
watching the log on the ai server (192.168.2.12) I see this when I ask a question:

```
2024-10-01T19:10:00.355548-04:00 ai ollama[1294755]: [GIN] 2024/10/01 - 19:10:00 | 403 |       8.741µs |     192.168.2.1 | OPTIONS  "/chat/completions"
2024-10-01T19:10:00.832976-04:00 ai ollama[1294755]: [GIN] 2024/10/01 - 19:10:00 | 403 |       7.715µs |     192.168.2.1 | OPTIONS  "/chat/completions"
2024-10-01T19:10:01.751960-04:00 ai ollama[1294755]: [GIN] 2024/10/01 - 19:10:01 | 403 |       6.443µs |     192.168.2.1 | OPTIONS  "/chat/completions"
```

**Comment by tens0rcat** [comment]
tried updating ollama. didn't help.  

I noticed in the hints for the new version it give the command you gave for running ollama on windows, which I am not.  The ai server is a linux box. Ubuntu 24.04 on a 10th gen i7 with an 8Gb 3070 GPU.

The ollama docs said to add this

```
Environment="OLLAMA_HOST=0.0.0.0"
```
 to the ollama.service file, but it didn't help.

**Comment by louis030195** [comment]
@tens0rcat 
can you right click in the app background then inspect then console, can also look at network tab, and see any errors?

your host is linux or windows?

ollama has 2 APIs, one if openai API compatible the other is their custom API


this is how we use ollama:

https://github.com/mediar-ai/screenpipe/blob/7ebb47883ecb9f9b5018d639e1979d2bd08ceb1e/screenpipe-app-tauri/components/search-chat.tsx#L334

through openai sdk, normal stuff, works for most people

**Comment by tens0rcat** [comment]
this should match http://*:11434

Yeah, in the console there is the CORS problem:

```
s to fetch at 'http://192.168.2.12:11434/chat/completions' from origin 'http://tauri.localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
15-a6ac48ef5a280942.js:232 
        
        
        POST http://192.168.2.12:11434/chat/completions net::ERR_FAILED
fetchWithTimeout @ 15-a6ac48ef5a280942.js:232
makeRequest @ 15-a6ac48ef5a280942.js:232
await in makeRequest
request @ 15-a6ac48ef5a280942.js:232
methodRequest @ 15-a6ac48ef5a280942.js:232
post @ 15-a6ac48ef5a280942.js:232
create @ 15-a6ac48ef5a280942.js:232
e4 @ page-5b2bb747041bb154.js:1
a_ @ fd9d1056-ad73cf74b6ee4fd5.js:1
aR @ fd9d1056-ad73cf74b6ee4fd5.js:1
(anonymous) @ fd9d1056-ad73cf74b6ee4fd5.js:1
sF @ fd9d1056-ad73cf74b6ee4fd5.js:1
sM @ fd9d1056-ad73cf74b6ee4fd5.js:1
(anonymous) @ fd9d1056-ad73cf74b6ee4fd5.js:1
o4 @ fd9d1056-ad73cf74b6ee4fd5.js:1
iV @ fd9d1056-ad73cf74b6ee4fd5.js:1
sU @ fd9d1056-ad73cf74b6ee4fd5.js:1
uR @ fd9d1056-ad73cf74b6ee4fd5.js:1
uM @ fd9d1056-ad73cf74b6ee4fd5.js:1
tauri.localhost/:1  Access to fetch at 'http://192.168.2.12:11434/chat/completions' from origin 'http://tauri.localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
15-a6ac48ef5a280942.js:232 
        
        
        POST http://192.168.2.12:11434/chat/completions net::ERR_FAILED
fetchWithTimeout @ 15-a6ac48ef5a280942.js:232
makeRequest @ 15-a6ac48ef5a280942.js:232
await in makeRequest
retryRequest @ 15-a6ac48ef5a280942.js:232
await in retryRequest
makeRequest @ 15-a6ac48ef5a280942.js:232
await in makeRequest
request @ 15-a6ac48ef5a280942.js:232
methodRequest @ 15-a6ac48ef5a280942.js:232
post @ 15-a6ac48ef5a280942.js:232
create @ 15-a6ac48ef5a280942.js:232
e4 @ page-5b2bb747041bb154.js:1
a_ @ fd9d1056-ad73cf74b6ee4fd5.js:1
aR @ fd9d1056-ad73cf74b6ee4fd5.js:1
(anonymous) @ fd9d1056-ad73cf74b6ee4fd5.js:1
sF @ fd9d1056-ad73cf74b6ee4fd5.js:1
sM @ fd9d1056-ad73cf74b6ee4fd5.js:1
(anonymous) @ fd9d1056-ad73cf74b6ee4fd5.js:1
o4 @ fd9d1056-ad73cf74b6ee4fd5.js:1
iV @ fd9d1056-ad73cf74b6ee4fd5.js:1
sU @ fd9d1056-ad73cf74b6ee4fd5.js:1
uR @ fd9d1056-ad73cf74b6ee4fd5.js:1
uM @ fd9d1056-ad73cf74b6ee4fd5.js:1
tauri.localhost/:1  Access to fetch at 'http://192.168.2.12:11434/chat/completions' from origin 'http://tauri.localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
15-a6ac48ef5a280942.js:232 
        
        
        POST http://192.168.2.12:11434/chat/completions net::ERR_FAILED
fetchWithTimeout @ 15-a6ac48ef5a280942.js:232
makeRequest @ 15-a6ac48ef5a280942.js:232
await in makeRequest
retryRequest @ 15-a6ac48ef5a280942.js:232
await in retryRequest
makeRequest @ 15-a6ac48ef5a280942.js:232
await in makeRequest
retryRequest @ 15-a6ac48ef5a280942.js:232
await in retryRequest
makeRequest @ 15-a6ac48ef5a280942.js:232
await in makeRequest
request @ 15-a6ac48ef5a280942.js:232
methodRequest @ 15-a6ac48ef5a280942.js:232
post @ 15-a6ac48ef5a280942.js:232
create @ 15-a6ac48ef5a280942.js:232
e4 @ page-5b2bb747041bb154.js:1
a_ @ fd9d1056-ad73cf74b6ee4fd5.js:1
aR @ fd9d1056-ad73cf74b6ee4fd5.js:1
(anonymous) @ fd9d1056-ad73cf74b6ee4fd5.js:1
sF @ fd9d1056-ad73cf74b6ee4fd5.js:1
sM @ fd9d1056-ad73cf74b6ee4fd5.js:1
(anonymous) @ fd9d1056-ad73cf74b6ee4fd5.js:1
o4 @ fd9d1056-ad73cf74b6ee4fd5.js:1
iV @ fd9d1056-ad73cf74b6ee4fd5.js:1
sU @ fd9d1056-ad73cf74b6ee4fd5.js:1
uR @ fd9d1056-ad73cf74b6ee4fd5.js:1
uM @ fd9d1056-ad73cf74b6ee4fd5.js:1
23-11c6d9b47f92bb66.js:1  Error generating AI response: ty: Connection error.
    at nU.makeRequest (http://tauri.localhost/_next/static/chunks/15-a6ac48ef5a280942.js:232:13537)
    at async e4 (http://tauri.localhost/_next/static/chunks/app/page-5b2bb747041bb154.js:1:131101)Caused by: TypeError: Failed to fetch
    at nU.fetchWithTimeout (15-a6ac48ef5a280942.js:232:15047)
    at nU.makeRequest (15-a6ac48ef5a280942.js:232:13365)
    at async e4 (page-5b2bb747041bb154.js:1:131101)
```

**Comment by tens0rcat** [comment]
This is probably the solution. https://gist.github.com/louis030195/988014691dae45cb5207be1d3cf1c317

**Comment by tens0rcat** [comment]
Nope, adding this to the ollama.service file did the trick 
```
Environment="OLLAMA_ORIGINS=*"
```

**Comment by tens0rcat** [comment]
Thank you for all your help!  I'm an old programmer, so not really a web guy.  Anyway, now I get to download some memory back. lol!

**Comment by mathjons** [comment]
> Nope, adding this to the ollama.service file did the trick
> 
> ```
> Environment="OLLAMA_ORIGINS=*"
> ```

Thanks tens0rcat 🙏

This fixed the CORS issue blocking Ollama for me on Windows 11:
1. Press Win + X and select "System"
2. Click on "Advanced system settings"
3. Click on "Environment Variables"
4. Under "System variables", click "New"
5. Set Variable name as "OLLAMA_ORIGINS" and Variable value as "*"
6. Click OK to save

**Comment by louis030195** [comment]
in latest version we provide an embedded ollama which uses this env var:

<img width="1312" alt="Screenshot 2024-10-22 at 11 26 50" src="https://github.com/user-attachments/assets/fce7546d-4bd6-42e2-868a-0c23d0d17b6b">

let me know how it goes
