### ISSUE TITLE
[question] bun tauri build failed

### ISSUE THREAD

**Issue by wqlxx** [mediar-ai/screenpipe#495]
I run the `bun tauri build `, and get the following error info:
```
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.mod.require (/home/ruijie/screenpipe-0.1.95/screenpipe-app-tauri/node_modules/next/dist/server/require-hook.js:65:28)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/ruijie/screenpipe-0.1.95/screenpipe-app-tauri/node_modules/next/dist/bin/next:7:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
error: script "build" exited with code 1
beforeBuildCommand `bun run build` failed with exit code 1
    Error beforeBuildCommand `bun run build` failed with exit code 1
error: script "tauri" exited with code 1
```
Does anyone have any solution to this problem? 
I have saved more error messages in the attachment.
[screen-pipe-app-tauri-error.txt](https://github.com/user-attachments/files/17361127/screen-pipe-app-tauri-error.txt)

**Comment by wqlxx** [comment]
> whats your os, version, etc what did you do?

ubuntu 22.04. Error is node.js version is too old. I change node.js from v12.22.x to v20.18.0. The problem
