### ISSUE TITLE
[bug] No audio captured from (working) microphone

### ISSUE THREAD

**Issue by ianmiell** [mediar-ai/screenpipe#674]
**describe the bug**
No audio is captured on the microphone.

If I speak into the Microphone on the list of audio devices, 'Macbook Pro Microphone (input) (default)' then nothing is picked up when I search for speech.

I checked in System Settings, and the microphone is selected as the default input, and is receiving input (the "Input Level" indicator moves up and down as I talk).

If I add "Display 1 (output) (default)" to the list of audio devices and play a video (very quietly), it is picked up and transcribed.

**to reproduce**
1. Start screenpipe
2. Add Display 1 (output) (default)
3. 

**expected behavior**
Audio should be captured from built-in microphone.

**system info**
- macos 14.3.1 (23D60)
- Version 0.10.9 (20241113.083853)

**additional context**
No errors in recorder logs 

```
[2m2024-11-13T11:37:19.360865Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: MacBook Pro Microphone (input), resampling from 48000 Hz to 16000 Hz    
[2m2024-11-13T11:37:19.436763Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: MacBook Pro Microphone (input), total audio frames processed: 321, frames that include speech: 0, speech duration: 0ms, speech ratio: 0.00, min required ratio: 0.05    
[2m2024-11-13T11:37:19.524845Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device MacBook Pro Microphone (input) received transcription Some("")    
[2m2024-11-13T11:37:19.524865Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device MacBook Pro Microphone (input) inserting audio chunk: ""    
[2m2024-11-13T11:37:19.914141Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Display 1 (output), resampling from 48000 Hz to 16000 Hz    
[2m2024-11-13T11:37:19.993784Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Display 1 (output), total audio frames processed: 321, frames that include speech: 246, speech duration: 24600ms, speech ratio: 0.77, min required ratio: 0.05    
[2m2024-11-13T11:37:21.152508Z[0m [32m INFO[0m [2mscreenpipe_audio::multilingual[0m[2m:[0m detected language: "en"    
[2m2024-11-13T11:37:22.070257Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:24.819338Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 1130s, Total Memory: 1% (0 GB / 16 GB), Total CPU: 28%, NPU: N/A
[2m2024-11-13T11:37:25.127960Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:27.192851Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m 0.0s -- 30.0s    
[2m2024-11-13T11:37:27.192860Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m   0.0s-0.0s:     
[2m2024-11-13T11:37:27.192902Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m   0.0s-24.6s:  relatively small investment of effort, problems can be halted before they get out of control. So goes the theory at least. That's basically the philosophy that keeps the DLR stations in good order. Tackle problems as soon as possible and you'll have a lot fewer problems to deal with. Well, I do hope you enjoyed today's video. If so, ple
<img width="985" alt="Screenshot 2024-11-13 at 12 38 35" src="https://github.com/user-attachments/assets/9d311f4e-a112-4e01-8eaa-4141837b5e1b">
ase do leave a like and perhaps subscribe for more if that's your jam. I would like to thank my donors on Ko-Fi, on Patreon and here on YouTube    
[2m2024-11-13T11:37:28.226025Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:28.391780Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m 30.0s -- 45.0s    
[2m2024-11-13T11:37:28.391788Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m   0.0s-0.0s:     
[2m2024-11-13T11:37:28.391791Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m   0.0s-30.0s:  So, let's go.    
[2m2024-11-13T11:37:28.954221Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device Display 1 (output) received transcription Some(" relatively small investment of effort, problems can be halted before they get out of control. So goes the theory at least. That's basically the philosophy that keeps the DLR stations in good order. Tackle problems as soon as possible and you'll have a lot fewer problems to deal with. Well, I do hope you enjoyed today's video. If so, please do leave a like and perhaps subscribe for more if that's your jam. I would like to thank my donors on Ko-Fi, on Patreon and here on YouTube\n")    
[2m2024-11-13T11:37:28.954240Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device Display 1 (output) inserting audio chunk: "/Users/imiell/.screenpipe/data/Display 1 (output)_2024-11-13_11-37-28.mp4"    
[2m2024-11-13T11:37:31.326433Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:34.426916Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:34.920716Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 1140s, Total Memory: 1% (0 GB / 16 GB), Total CPU: 44%, NPU: N/A
[2m2024-11-13T11:37:37.550383Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:40.591551Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:43.693603Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:45.008141Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 1150s, Total Memory: 2% (0 GB / 16 GB), Total CPU: 41%, NPU: N/A
[2m2024-11-13T11:37:46.792705Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:49.370955Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: MacBook Pro Microphone (input), resampling from 48000 Hz to 16000 Hz    
[2m2024-11-13T11:37:49.462852Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: MacBook Pro Microphone (input), total audio frames processed: 321, frames that include speech: 0, speech duration: 0ms, speech ratio: 0.00, min required ratio: 0.05    
[2m2024-11-13T11:37:49.532691Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device MacBook Pro Microphone (input) received transcription Some("")    
[2m2024-11-13T11:37:49.532710Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device MacBook Pro Microphone (input) inserting audio chunk: ""    
[2m2024-11-13T11:37:49.894726Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:49.939635Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Display 1 (output), resampling from 48000 Hz to 16000 Hz    
[2m2024-11-13T11:37:50.027059Z[0m [32m INFO[0m [2mscreenpipe_audio::stt[0m[2m:[0m device: Display 1 (output), total audio frames processed: 321, frames that include speech: 65, speech duration: 6500ms, speech ratio: 0.20, min required ratio: 0.05    
[2m2024-11-13T11:37:51.144544Z[0m [32m INFO[0m [2mscreenpipe_audio::multilingual[0m[2m:[0m detected language: "en"    
[2m2024-11-13T11:37:52.992878Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:54.168707Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m 0.0s -- 30.0s    
[2m2024-11-13T11:37:54.168715Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m   0.0s-0.0s:     
[2m2024-11-13T11:37:54.168727Z[0m [32m INFO[0m [2mscreenpipe_audio::whisper[0m[2m:[0m   0.0s-6.3s:  on Patreon and here on YouTube for your support. You are the applied philosophy to my social problems. I'll see you all again very soon.    
[2m2024-11-13T11:37:54.607092Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device Display 1 (output) received transcription Some(" on Patreon and here on YouTube for your support. You are the applied philosophy to my social problems. I'll see you all again very soon.\n")    
[2m2024-11-13T11:37:54.607106Z[0m [32m INFO[0m [2mscreenpipe_server::core[0m[2m:[0m device Display 1 (output) inserting audio chunk: "/Users/imiell/.screenpipe/data/Display 1 (output)_2024-11-13_11-37-54.mp4"    
[2m2024-11-13T11:37:55.081748Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 1161s, Total Memory: 3% (0 GB / 16 GB), Total CPU: 35%, NPU: N/A
[2m2024-11-13T11:37:56.092068Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:37:59.194374Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:38:02.290591Z[0m [32m INFO[0m [2mscreenpipe_server::server[0m[2m:[0m streaming frames from 2024-11-12 23:01:00 UTC to 2024-11-13 09:08:48.188 UTC    
[2m2024-11-13T11:38:05.182686Z[0m [32m INFO[0m [2mscreenpipe_server::resource_monitor[0m[2m:[0m Runtime: 1171s, Total Memory: 1% (0 GB / 16 GB), Total CPU: 22%, NPU: N/A
```

**Comment by louis030195** [comment]
@ianmiell can you try updating your macos version? likely solve the problem

**Comment by ianmiell** [comment]
Upgraded to:

15.1 (24B83)

(Sequoia)

No joy. Permissions look OK to me (I deleted screenpipe permissions on
Screen&System Audio Recording and reinstated and restarted a few times).

This was working a few days ago.

Note that I compile from source against latest main.

**Comment by ianmiell** [comment]
This was a permissions thing. For some reason, on MacOS it doesn't ask for Microphone permissions, even if you removed the permission and then restarted screenpipe, or asked screenpipe to sort out permissions (in troubleshooting).

In the end, I had to delete everything related to screenpipe I could find across my Mac, and then rebuild. Once that was done, on restart it asked for microphone permissions and started recording again.

**Comment by ianmiell** [comment]
Still a problem on a rebuild. The microphone permission stops working. I remove the microphone permission with:

`tccutil reset Microphone "screenpi.pe"`

then I try and remove everything else:

```
rm -rf ~/.screenpipe
rm -rf ~/Library/*/screenpipe
rm -rf ~/Library/*/screenpi.pe
rm -rf ~/Library/*/screenpi.pe.savedState
rm -rf ~/Volumes/*/screenpipe.app
```

and remove the existing 'Screen & System Audio Recording' permission by hand (tccutil doesn't work for that one for some reason).

Then I rebuild and reinstall, and then starting up fails to pick up the microphone input.

It still sometimes seems to work, sometimes not without any consistency. I'm still trying to find a pattern that works. Some combination of running the screenpipe.app binary manually from the command line and screenpipe binary sometimes works, but I can't find a reproducible set of steps.

Is there any way I can debug this further?

**Comment by ianmiell** [comment]
Is it maybe related to challenges with audio here?

https://github.com/mediar-ai/screenpipe/issues/70

**Comment by ianmiell** [comment]
Latest version, I see this error:

```
2024-11-24T12:57:04.082882Z  INFO screenpipe_audio::stt: device: MacBook Pro Microphone (input), speech ratio: 0.81, min_speech_ratio: 0.2, audio_frames: 478676, speech_frames: 243
2024-11-24T12:57:04.618116Z ERROR screenpipe_app::sidecar: Sidecar stderr: thread '<unnamed>' panicked at screenpipe-audio/src/stt.rs:395:21:

2024-11-24T12:57:04.618139Z ERROR screenpipe_app::sidecar: Sidecar stderr: byte index 8 is out of bounds of ``

2024-11-24T12:57:04.618147Z ERROR screenpipe_app::sidecar: Sidecar stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2024-11-24T12:57:04.619895Z ERROR screenpipe_app::sidecar: Sidecar stderr: thread 'tokio-runtime-worker' panicked at screenpipe-audio/src/stt.rs:178:19:

2024-11-24T12:57:04.619912Z ERROR screenpipe_app::sidecar: Sidecar stderr: called `Result::unwrap()` on an `Err` value: Any { .. }

2024-11-24T12:57:04.910169Z  INFO screenpipe_server::se
```

**Comment by ianmiell** [comment]
Again, with more context and RUST_BACKTRACE set on:

```
2024-11-24T12:58:54.120362Z  INFO screenpipe_server::server: search completed: found 1 results
2024-11-24T12:58:54.867308Z  INFO screenpipe_server::resource_monitor: Runtime: 10s, Total Memory: 2% (0 GB / 16 GB), Total CPU: 0%, NPU: N/A
2024-11-24T12:58:56.750010Z  INFO screenpipe_server::server: streaming frames from 2024-11-24 00:01:00 UTC to 2024-11-24 12:56:07.190 UTC
2024-11-24T12:58:59.763489Z  INFO screenpipe_audio::core: starting continuous recording for Display 1 (output) (5s segments)
2024-11-24T12:58:59.787901Z  INFO screenpipe_audio::core: starting continuous recording for MacBook Pro Microphone (input) (5s segments)
2024-11-24T12:58:59.847324Z  INFO screenpipe_server::server: streaming frames from 2024-11-24 00:01:00 UTC to 2024-11-24 12:56:07.190 UTC
2024-11-24T12:59:02.948434Z  INFO screenpipe_server::server: streaming frames from 2024-11-24 00:01:00 UTC to 2024-11-24 12:56:07.190 UTC
2024-11-24T12:59:04.797824Z  INFO screenpipe_audio::stt: device: Display 1 (output), speech ratio: 0, min_speech_ratio: 0.2, audio_frames: 78676, speech_frames: 0
2024-11-24T12:59:04.810981Z  INFO screenpipe_audio::stt: device: MacBook Pro Microphone (input), speech ratio: 0.82, min_speech_ratio: 0.2, audio_frames: 80000, speech_frames: 41
2024-11-24T12:59:04.929780Z ERROR screenpipe_app::sidecar: Sidecar stderr: thread '<unnamed>' panicked at screenpipe-audio/src/stt.rs:395:21:

2024-11-24T12:59:04.929803Z ERROR screenpipe_app::sidecar: Sidecar stderr: byte index 8 is out of bounds of ``

2024-11-24T12:59:04.929810Z ERROR screenpipe_app::sidecar: Sidecar stderr: stack backtrace:

2024-11-24T12:59:04.941591Z ERROR screenpipe_app::sidecar: Sidecar stderr:    0: _rust_begin_unwind

2024-11-24T12:59:04.941608Z ERROR screenpipe_app::sidecar: Sidecar stderr:    1: core::panicking::panic_fmt

2024-11-24T12:59:04.941615Z ERROR screenpipe_app::sidecar: Sidecar stderr:    2: core::str::slice_error_fail_rt

2024-11-24T12:59:04.941622Z ERROR screenpipe_app::sidecar: Sidecar stderr:    3: core::str::slice_error_fail

2024-11-24T12:59:04.941641Z ERROR screenpipe_app::sidecar: Sidecar stderr:    4: screenpipe_audio::stt::stt::{{closure}}

2024-11-24T12:59:04.941656Z ERROR screenpipe_app::sidecar: Sidecar stderr:    5: tokio::runtime::park::CachedParkThread::block_on

2024-11-24T12:59:04.941679Z ERROR screenpipe_app::sidecar: Sidecar stderr:    6: tokio::runtime::context::runtime::enter_runtime

2024-11-24T12:59:04.941719Z ERROR screenpipe_app::sidecar: Sidecar stderr:    7: tokio::runtime::runtime::Runtime::block_on

2024-11-24T12:59:04.942957Z ERROR screenpipe_app::sidecar: Sidecar stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

2024-11-24T12:59:04.944365Z ERROR screenpipe_app::sidecar: Sidecar stderr: thread 'tokio-runtime-worker' panicked at screenpipe-audio/src/stt.rs:178:19:

2024-11-24T12:59:04.944373Z ERROR screenpipe_app::sidecar: Sidecar stderr: called `Result::unwrap()` on an `Err` value: Any { .. }

2024-11-24T12:59:04.944436Z ERROR screenpipe_app::sidecar: Sidecar stderr: stack backtrace:

2024-11-24T12:59:04.944466Z ERROR screenpipe_app::sidecar: Sidecar stderr:    0: _rust_begin_unwind

2024-11-24T12:59:04.944474Z ERROR screenpipe_app::sidecar: Sidecar stderr:    1: core::panicking::panic_fmt

2024-11-24T12:59:04.944523Z ERROR screenpipe_app::sidecar: Sidecar stderr:    2: core::result::unwrap_failed

2024-11-24T12:59:04.944530Z ERROR screenpipe_app::sidecar: Sidecar stderr:    3: screenpipe_audio::stt::stt_sync

2024-11-24T12:59:04.944555Z ERROR screenpipe_app::sidecar: Sidecar stderr:    4: objc::rc::autorelease::autoreleasepool

2024-11-24T12:59:04.944562Z ERROR screenpipe_app::sidecar: Sidecar stderr:    5: screenpipe_audio::stt::create_whisper_channel::{{closure}}::{{closure}}

2024-11-24T12:59:04.944569Z ERROR screenpipe_app::sidecar: Sidecar stderr:    6: tokio::runtime::task::core::Core<T,S>::poll

2024-11-24T12:59:04.944576Z ERROR screenpipe_app::sidecar: Sidecar stderr:    7: tokio::runtime::task::harness::Harness<T,S>::poll

2024-11-24T12:59:04.944581Z ERROR screenpipe_app::sidecar: Sidecar stderr:    8: tokio::runtime::scheduler::multi_thread::worker::Context::run_task

2024-11-24T12:59:04.944588Z ERROR screenpipe_app::sidecar: Sidecar stderr:    9: tokio::runtime::scheduler::multi_thread::worker::Context::run

2024-11-24T12:59:04.944594Z ERROR screenpipe_app::sidecar: Sidecar stderr:   10: tokio::runtime::context::runtime::enter_runtime

2024-11-24T12:59:04.944599Z ERROR screenpipe_app::sidecar: Sidecar stderr:   11: tokio::runtime::scheduler::multi_thread::worker::run

2024-11-24T12:59:04.944607Z ERROR screenpipe_app::sidecar: Sidecar stderr:   12: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll

2024-11-24T12:59:04.944613Z ERROR screenpipe_app::sidecar: Sidecar stderr:   13: tokio::runtime::task::core::Core<T,S>::poll

2024-11-24T12:59:04.944619Z ERROR screenpipe_app::sidecar: Sidecar stderr:   14: tokio::runtime::task::harness::Harness<T,S>::poll

2024-11-24T12:59:04.944625Z ERROR screenpipe_app::sidecar: Sidecar stderr:   15: tokio::runtime::blocking::pool::Inner::run

2024-11-24T12:59:04.944650Z ERROR screenpipe_app::sidecar: Sidecar stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

2024-11-24T12:59:04.979340Z  INFO screenpipe_server::resource_monitor: Runtime: 20s, Total Memory: 4% (1 GB / 16 GB), Total CPU: 48%, NPU: N/A
2024-11-24T12:59:06.047513Z  INFO screenpipe_server::server: streaming frames from 2024-11-24 00:01:00 UTC to 2024-11-24 12:56:07.190 UTC
2024-11-24T12:59:06.713159Z DEBUG screenpipe_app::sidecar: interval: 0
2024-11-24T12:59:06.713173Z DEBUG screenpipe_app::sidecar: interval: 0
2024-11-24T12:59:06.713175Z DEBUG screenpipe_app::sidecar: last_restart: Instant { tv_sec: 162328, tv_nsec: 396902750 }
2024-11-24T12:59:06.713177Z DEBUG screenpipe_app::sidecar: elapsed: 22.588378416s
2024-11-24T12:59:09.144663Z  INFO screenpipe_server::server: streaming frames from 2024-11-24 00:01:00 UTC to 2024-11-24 12:56:07.190 UTC
2024-11-24T12:59:09.788866Z ERROR screenpipe_audio::core: whisper channel disconnected, restarting recording process
2024-11-24T12:59:09.788934Z ERROR screenpipe_audio::core: record_and_transcribe error, restarting: Whisper channel disconnected
2024-11-24T12:59:09.791569Z ERROR screenpipe_audio::core: whisper channel disconnected, restarting recording process
2024-11-24T12:59:09.792190Z ERROR screenpipe_audio::core: record_and_transcribe error, restarting: Whisper channel disconnected
```

**Comment by ianmiell** [comment]
Recent changes seem to have fixed this/made it easier to manage permissions.
