### ISSUE TITLE
[bounty] $100 windows installation fails for a new user, logs attached

### ISSUE THREAD

**Issue by m13v** [mediar-ai/screenpipe#764]
1. I downloaded screenpipe on windows machine
2. started it, the setup failed
3. I pulled up the inspector and looked at the console, this is the error I found

error or timeout: Error: command failed with code -1073741515
    at page-2bff8a7bfd23260b.js:1:174911
    at f.emit (590-d9ad7e6472c4fddd.js:276:162075)
    at n.onmessage (590-d9ad7e6472c4fddd.js:276:163069)
    at 590-d9ad7e6472c4fddd.js:276:160962
    at value (<anonymous>:229:30)

**Comment by louis030195** [comment]
@Neptune650 this is not solved fyi, if you want to help!

i believe issue is on `screenpipe setup` subcommand

https://github.com/mediar-ai/screenpipe/blob/014c209e164b68dc6d2138adc6559cff7ca53bcc/screenpipe-app-tauri/components/onboarding/status.tsx#L43

is this subcommand actually working on windows?

https://github.com/mediar-ai/screenpipe/blob/014c209e164b68dc6d2138adc6559cff7ca53bcc/screenpipe-server/src/bin/screenpipe-server.rs#L145

i think solving this would also solve the troubleshooting button in settings which does not seem to work on windows (using same subcommand)

**Comment by Neptune650** [comment]
> @Neptune650 this is not solved fyi, if you want to help!
> 
> i believe issue is on `screenpipe setup` subcommand
> 
> https://github.com/mediar-ai/screenpipe/blob/014c209e164b68dc6d2138adc6559cff7ca53bcc/screenpipe-app-tauri/components/onboarding/status.tsx#L43
> 
> is this subcommand actually working on windows?
> 
> https://github.com/mediar-ai/screenpipe/blob/014c209e164b68dc6d2138adc6559cff7ca53bcc/screenpipe-server/src/bin/screenpipe-server.rs#L145
> 
> i think solving this would also solve the troubleshooting button in settings which does not seem to work on windows (using same subcommand)

@louis030195 Of course, will look into it, will use a Windows VM for testing.

**Comment by m13v** [comment]
thx Neptune, looking forward

**Comment by Neptune650** [comment]
> 1. I downloaded screenpipe on windows machine
> 
>     2. started it, the setup failed
> 
>     3. I pulled up the inspector and looked at the console, this is the error I found
> 
> 
> error or timeout: Error: command failed with code -1073741515 at page-2bff8a7bfd23260b.js:1:174911 at f.emit (590-d9ad7e6472c4fddd.js:276:162075) at n.onmessage (590-d9ad7e6472c4fddd.js:276:163069) at 590-d9ad7e6472c4fddd.js:276:160962 at value (:229:30)

@m13v  Do we have the entire logs? We do need to know what step is failing, could also be a network issue at the user side

**Comment by m13v** [comment]
Oh, that’s the worst thing, I can’t see any other details for the error
