### ISSUE TITLE
[bug] macos build broken

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#799]
macos build broken (both `bun tauri build` and `bun tauri dev`

```
-verify v0.2.1
   Compiling sync_wrapper v0.1.2
   Compiling tower-http v0.4.4
error: failed to run custom build command for `***-app v0.14.4 (/Users/runner/work/***/***/***-app-tauri/src-tauri)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/runner/work/***/***/***-app-tauri/src-tauri/target/release/build/***-app-fb83144bf23477b7/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:45:18:
  failed to copy *** binary: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
     1: core::panicking::panic_fmt
               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
     2: core::result::unwrap_failed
               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
failed to build app: failed to build app
    Error [tauri_cli_node] failed to build app: failed to build app
Error: Command failed with exit code 1: bunx tauri -v build --target x86_64-apple-darwin
0s
0s
0s
```

@Neptune650

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/actions/runs/12075491583/job/33675373638

**Comment by Neptune650** [comment]
Will look into this

**Comment by Neptune650** [comment]
> macos build broken (both `bun tauri build` and `bun tauri dev`
> 
> ```
> -verify v0.2.1
>    Compiling sync_wrapper v0.1.2
>    Compiling tower-http v0.4.4
> error: failed to run custom build command for `***-app v0.14.4 (/Users/runner/work/***/***/***-app-tauri/src-tauri)`
> note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
> 
> Caused by:
>   process didn't exit successfully: `/Users/runner/work/***/***/***-app-tauri/src-tauri/target/release/build/***-app-fb83144bf23477b7/build-script-build` (exit status: 101)
>   --- stderr
>   thread 'main' panicked at build.rs:45:18:
>   failed to copy *** binary: Os { code: 2, kind: NotFound, message: "No such file or directory" }
>   stack backtrace:
>      0: rust_begin_unwind
>                at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
>      1: core::panicking::panic_fmt
>                at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
>      2: core::result::unwrap_failed
>                at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
>      3: core::result::Result<T,E>::expect
>      4: build_script_build::main
>      5: core::ops::function::FnOnce::call_once
>   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> warning: build failed, waiting for other jobs to finish...
> failed to build app: failed to build app
>     Error [tauri_cli_node] failed to build app: failed to build app
> Error: Command failed with exit code 1: bunx tauri -v build --target x86_64-apple-darwin
> 0s
> 0s
> 0s
> ```
> 
> @Neptune650

![image](https://github.com/user-attachments/assets/a1f91f14-acf2-4730-9117-85d2aaad5c3b)
![image](https://github.com/user-attachments/assets/aa28f433-727c-44bf-aaec-40bb2cf9f7eb)

@louis030195 This is extremely weird, it seems it's compiling the Rust conditional for ARM64 despite the fact that the target is set to x86_64, possible Cargo bug?
