### ISSUE TITLE
windows install screenpipe didnt work

### ISSUE THREAD

**Issue by rmchndrng** [mediar-ai/screenpipe#817]
Following the steps mentioned at https://docs.screenpi.pe/docs/getting-started#windows-installation-experimental

1. install required tools: - Ran without issues
2. environment variables - Set the env variables
3. clone and build: 

* Note: Had to manually install cmake and wget

The following steps worked

```
# clone the repo
git clone https://github.com/mediar-ai/screenpipe
cd screenpipe
 
# build the cli
cargo build --release
 
# build the desktop app
cd screenpipe-app-tauri
bun install
```

But ran into error when I ran

```
bun scripts/pre_build.js
```

```log
Extracting Ollama...

GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsB...
At C:\program files\powershell\7\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:969 char:13
+             throw $invalidFileFormatException
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileFormatException
    + FullyQualifiedErrorId :

error installing ollama sidecar: 12 | export default "unknown";
                    ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "At C:\\program files\\powershell\\7\\Modules\\Microsoft.PowerShell.Archive\\Microsoft.PowerShell.Archive.psm1:969 char:13\r\n+             throw $invalidFileFormatException\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : OperationStopped: (:) [], FileFormatException\r\n    + FullyQualifiedErrorId : \r\n \r\n",
  "stdout": "\r\nGAC    Version        Location
                \r\n---    -------        --------
                   \r\nTrue   v4.0.30319     C:\\WINDOWS\\Microsoft.Net\\assembly\\GAC_MSIL\\WindowsBase\\v4.0_4.0.0.0__31bf3856ad364e35\\WindowsB...\r\n"
}

      at new ShellError (unknown:12:16)
      at new ShellPromise (unknown:72:16)
      at BunShell (unknown:187:35)
      at C:\screenpipe\screenpipe\screenpipe-app-tauri\scripts\pre_build.js:535:10

12 | export default "unknown";
                    ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "At C:\\program files\\powershell\\7\\Modules\\Microsoft.PowerShell.Archive\\Microsoft.PowerShell.Archive.psm1:969 char:13\r\n+             throw $invalidFileFormatException\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : OperationStopped: (:) [], FileFormatException\r\n    + FullyQualifiedErrorId : \r\n \r\n",
  "stdout": "\r\nGAC    Version        Location
                \r\n---    -------        --------
                   \r\nTrue   v4.0.30319     C:\\WINDOWS\\Microsoft.Net\\assembly\\GAC_MSIL\\WindowsBase\\v4.0_4.0.0.0__31bf3856ad364e35\\WindowsB...\r\n"
}

      at new ShellError (unknown:12:16)
      at new ShellPromise (unknown:72:16)
      at BunShell (unknown:187:35)
      at C:\screenpipe\screenpipe\screenpipe-app-tauri\scripts\pre_build.js:535:10
```
[screenpipe_pre_build_error.log](https://github.com/user-attachments/files/17974271/screenpipe_pre_build_error.log)

Please let me know if you need additional information.

**Comment by louis030195** [comment]
did you try to download the pre built app before building from source? https://screenpi.pe/

not sure about your issue, i wont be more helpful than chatgpt
