### ISSUE TITLE
[bug] ZodError: Expected string, received number

### ISSUE THREAD

**Issue by natea** [mediar-ai/screenpipe#985]
**describe the bug**

I've set up the Obsidian Time Logs pipe and confirmed that it's working by seeing the time entries appearing in Obsidian, but when I look at the logs, it appears that there is an error occurring. (see below)

**system info**
- os: macos 10.15.1.1
- screenpipe version: 0.17.5 (20241214.235553)

**additional context**

Here is what I see in the logs:

```
2024-12-16T05:08:07.261578Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] error in work log pipeline: 14 |   constructor({
2024-12-16T05:08:07.261621Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 15 |     name: name14,
2024-12-16T05:08:07.261629Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 16 |     message,
2024-12-16T05:08:07.261636Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 17 |     cause
2024-12-16T05:08:07.261642Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 18 |   }) {
2024-12-16T05:08:07.261650Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 19 |     super(message);
2024-12-16T05:08:07.261656Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]          ^
2024-12-16T05:08:07.261913Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] AI_TypeValidationError: Type validation failed: Value: {"title":"Automated Monitoring of Screenpipe Activity","description":"Conducted automated monitoring of screenpipe activity, including pipe execution and action server listening.","tags":["#automatedmonitoring","#mediar-ai","#screenpipe"],"timeSpent":5}.
2024-12-16T05:08:07.261926Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] Error message: [
2024-12-16T05:08:07.261932Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]   {
2024-12-16T05:08:07.261940Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "code": "invalid_type",
2024-12-16T05:08:07.261948Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "expected": "string",
2024-12-16T05:08:07.261954Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "received": "number",
2024-12-16T05:08:07.261960Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "path": [
2024-12-16T05:08:07.261966Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       "timeSpent"
2024-12-16T05:08:07.261972Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     ],
2024-12-16T05:08:07.261978Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "message": "Expected string, received number"
2024-12-16T05:08:07.262453Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]   }
2024-12-16T05:08:07.262460Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] ]
2024-12-16T05:08:07.262468Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at new _AISDKError (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/@ai-sdk/provider/dist/index.mjs:19:5)
2024-12-16T05:08:07.262642Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at new _TypeValidationError (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/@ai-sdk/provider/dist/index.mjs:368:1)
2024-12-16T05:08:07.262651Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at wrap (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/@ai-sdk/provider/dist/index.mjs:324:90)
2024-12-16T05:08:07.263048Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at safeValidateTypes (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/@ai-sdk/provider-utils/dist/index.mjs:306:3)
2024-12-16T05:08:07.263055Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at /Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/ai/dist/index.mjs:2838:47
2024-12-16T05:08:07.263059Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at processTicksAndRejections (native:7:39)
2024-12-16T05:08:07.263062Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]
2024-12-16T05:08:07.263065Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 159 |     const json = JSON.stringify(obj, null, 2);
2024-12-16T05:08:07.263068Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 160 |     return json.replace(/"([^"]+)":/g, "$1:");
2024-12-16T05:08:07.263178Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 161 | };
2024-12-16T05:08:07.263183Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 162 | class ZodError extends Error {
2024-12-16T05:08:07.263187Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 163 |     constructor(issues) {
2024-12-16T05:08:07.263190Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] 164 |         super();
2024-12-16T05:08:07.263193Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]               ^
2024-12-16T05:08:07.263196Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] ZodError: [
2024-12-16T05:08:07.263212Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]   {
2024-12-16T05:08:07.263215Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "code": "invalid_type",
2024-12-16T05:08:07.263217Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "expected": "string",
2024-12-16T05:08:07.263220Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "received": "number",
2024-12-16T05:08:07.263222Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "path": [
2024-12-16T05:08:07.263224Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       "timeSpent"
2024-12-16T05:08:07.263226Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     ],
2024-12-16T05:08:07.263229Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "message": "Expected string, received number"
2024-12-16T05:08:07.263292Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]   }
2024-12-16T05:08:07.263308Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] ]
2024-12-16T05:08:07.263316Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]  errors: [
2024-12-16T05:08:07.263323Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]   {
2024-12-16T05:08:07.263332Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "code": "invalid_type",
2024-12-16T05:08:07.263339Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "expected": "string",
2024-12-16T05:08:07.263346Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "received": "number",
2024-12-16T05:08:07.263353Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "path": [
2024-12-16T05:08:07.263359Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       "timeSpent"
2024-12-16T05:08:07.263365Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     ],
2024-12-16T05:08:07.263373Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]     "message": "Expected string, received number"
2024-12-16T05:08:07.263379Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]   }
2024-12-16T05:08:07.263385Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs] ]
2024-12-16T05:08:07.263390Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]
2024-12-16T05:08:07.263397Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at new ZodError (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/zod/lib/index.mjs:164:9)
2024-12-16T05:08:07.263405Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at error (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/zod/lib/index.mjs:587:31)
2024-12-16T05:08:07.263444Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at validate (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/@ai-sdk/ui-utils/dist/index.mjs:1331:98)
2024-12-16T05:08:07.263453Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at safeValidateTypes (/Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/@ai-sdk/provider-utils/dist/index.mjs:228:31)
2024-12-16T05:08:07.263464Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]       at /Users/nateaune/.screenpipe/pipes/pipe-obsidian-time-logs/node_modules/ai/dist/index.mjs:2396:47
2024-12-16T05:08:07.263474Z ERROR screenpipe_core::pipes::pipes: [pipe-obsidian-time-logs]
```

**Comment by louis030195** [comment]
yes this the reason: https://en.wikipedia.org/wiki/Hallucination_(artificial_intelligence)

just wait the next iteration and it will work, or pick a bigger/better model

it will hallucinate 5-10% of the time depending on the model
